# Nixpacks configuration for TOIT monorepo
[build]
cmd = "npm run build --filter=portal-toit"

[start]
cmd = "npm run portal:dev"

[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci"]