# Nixpacks configuration for TOIT monorepo
[variables]
NODE_ENV = "production"
PORT = "3000"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]  
cmds = ["npm run build --filter=portal-toit"]

[start]
cmd = "npm run portal:dev"