# Railway Configuration for TRADia Platform

# Build Configuration
[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
watchPatterns = ["**/*.ts", "**/*.js", "**/*.json"]

# Development Environment
[environments.development]
PORT = 3000
NODE_ENV = "development"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
REDIS_URL = "${{Redis.REDIS_URL}}"
JWT_SECRET = "${{JWT_SECRET_DEV}}"
WHATSAPP_API_KEY = "${{WHATSAPP_API_KEY}}"
EMAIL_API_KEY = "${{EMAIL_API_KEY}}"
FRONTEND_URL = "https://tradia-dev.up.railway.app"

[environments.development.deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Testing Environment  
[environments.testing]
PORT = 3000
NODE_ENV = "test"
DATABASE_URL = "${{Postgres_Test.DATABASE_URL}}"
REDIS_URL = "${{Redis_Test.REDIS_URL}}"
JWT_SECRET = "${{JWT_SECRET_TEST}}"
WHATSAPP_API_KEY = "${{WHATSAPP_API_KEY}}"
EMAIL_API_KEY = "${{EMAIL_API_KEY}}"
FRONTEND_URL = "https://tradia-test.up.railway.app"

[environments.testing.deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Production Environment
[environments.production]
PORT = 3000
NODE_ENV = "production"
DATABASE_URL = "${{Postgres_Prod.DATABASE_URL}}"
REDIS_URL = "${{Redis_Prod.REDIS_URL}}"
JWT_SECRET = "${{JWT_SECRET_PROD}}"
WHATSAPP_API_KEY = "${{WHATSAPP_API_KEY}}"
EMAIL_API_KEY = "${{EMAIL_API_KEY}}"
FRONTEND_URL = "https://tradia.up.railway.app"

[environments.production.deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Services Configuration
[services.backend]
source = "backend"
domains = [
  "tradia-api-dev.up.railway.app",
  "tradia-api-test.up.railway.app", 
  "tradia-api.up.railway.app"
]

[services.frontend]
source = "frontend"
domains = [
  "tradia-dev.up.railway.app",
  "tradia-test.up.railway.app",
  "tradia.up.railway.app"
]

# Database Services
[services.postgres-dev]
plugin = "postgresql"
plan = "hobby"

[services.postgres-test]
plugin = "postgresql"
plan = "hobby"

[services.postgres-prod]
plugin = "postgresql"
plan = "pro"

[services.redis-dev]
plugin = "redis"
plan = "hobby"

[services.redis-test]
plugin = "redis"
plan = "hobby"

[services.redis-prod]
plugin = "redis"
plan = "pro"
